sudo: required

services:
  - docker

before_install:
  - docker build -t superknife0512/fe-react -f Dockerfile.dev ./fe-react

scripts:
  - docker run -e CI=true superknife0512/fe-react npm test

after_install:
  - docker build -t superknife0512/fe-react ./fe-react
  - docker build -t superknife0512/server ./server
  - docker build -t superknife0512/nginx ./nginx
  - docker build -t superknife0512/worker ./worker
  # login with docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image
  - docker push superknife0512/fe-react
  - docker push superknife0512/server
  - docker push superknife0512/nginx
  - docker push superknife0512/worker
