sudo: required

services:
  - docker

before_install:
  - docker build -t superknife0512/fe-react -f ./fe-react/Dockerfile.dev ./fe-react

scripts:
  - docker run -e CI=true superknife0512/fe-react npm test

after_success:
  - docker build -t superknife0512/multi-fe-react ./fe-react
  - docker build -t superknife0512/multi-server ./server
  - docker build -t superknife0512/multi-nginx ./nginx
  - docker build -t superknife0512/multi-worker ./worker
  # login with docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image
  - docker push superknife0512/multi-fe-react
  - docker push superknife0512/multi-server
  - docker push superknife0512/multi-nginx
  - docker push superknife0512/multi-worker
  - echo "DONE"
