version: "3"
services:
  redis:
    image: "redis:latest"
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Toan1234
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3500:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./server:/home/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_PORT=5432
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=Toan1234
      - PG_DATABASE=postgres
    depends_on:
      - redis
      - postgres
  client:
    build:
      context: ./fe-react
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./fe-react:/home/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./worker:/home/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
